apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/zendev2112/pipeline-devops-app
    newTag: latest
